apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: shell-container
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      stdin: true
      tty: true
      resources:
        limits:
          memory: "256Mi"
          cpu: "100m"