# values.yaml
namespace: carat-stg
image:
  # repository: $DOCKER_ACCOUNT/$IMAGE_NAME
  repository_ref: "altonium/carat-core-stg:latest"
  pullPolicy: Always

service:
  name: carat-core-stg
  type: ClusterIP
  port: 80

spec:
  replicas: 2

log:
  jobname: cco-stg

app:
  port: 3000  # Internal port where NestJS is running

env:
  DATABASE_HOST: "10.8.200.181"
  DATABASE_PORT: "5432"
  DATABASE_USER: "kilua"
  DATABASE_NAME: "carat-stg"

  DATABASE2_HOST: "10.8.200.181"
  DATABASE2_PORT: "5432"
  DATABASE2_USER: "kilua"
  DATABASE2_NAME: "carat-stg"

  REDIS_HOST: "10.8.200.182"
  REDIS_PORT: "6379"
  REDIS_PREFIX: "ccos"
  REDIS2_HOST: "10.8.200.182"
  REDIS2_PORT: "6379"
  CARAT_DISBURSE_HOST: "10.8.3.146"
  CARAT_DISBURSE_PORT: "3500"
  CARAT_SIGNER_HOST: "10.8.3.146"
  CARAT_SIGNER_PORT: "4500"

  APP_ENV: "stg"
  NETZ_MERCHANT_DAILY_LIMIT_IDRM: 38
  NETZ_MERCHANT_MONTHLY_LIMIT_IDRM: 1000
  NETZ_MERCHANT_ANNUAL_LIMIT_IDRM: 3800
  NETZME_BASE_URL: "https://tokoapisnap-stg.netzme.com"

  MOCK_DATA: false
  MOCK_NETZME_BASE_URL: http://carat.wp68.uk/netzme

secretName: carat-stg-secrets

resources: {}