# values.yaml
namespace: carat-stg
image:
  # repository: $DOCKER_ACCOUNT/$IMAGE_NAME
  repository_ref: "altonium/carat-dash-be-stg:latest"
  pullPolicy: Always

service:
  name: carat-dash-be-stg
  type: ClusterIP
  port: 80

spec:
  replicas: 1

log:
  jobname: cdb-stg

app:
  port: 3000  # Internal port where NestJS is running

env:
  DATABASE_HOST: "10.8.200.181"
  DATABASE_PORT: "5432"
  DATABASE_USER: "kilua"
  DATABASE_NAME: "carat-stg"

  DATABASE2_HOST: "10.8.200.181"
  DATABASE2_PORT: "5432"
  DATABASE2_USER: "kilua"
  DATABASE2_NAME: "carat-stg"

  REDIS_HOST: "10.8.200.182"
  REDIS_PORT: "6379"
  REDIS_PREFIX: "cdbs"

  REDIS2_HOST: "10.8.200.182"
  REDIS2_PORT: "6379"

  APP_ENV: "stg"

secretName: carat-stg-secrets

resources: {}