# values.yaml
namespace: carat-prd
image:
  # repository: $DOCKER_ACCOUNT/$IMAGE_NAME
  repository_ref: "altonium/carat-dash-be-prd:latest"
  pullPolicy: Always

service:
  name: cdb-prd
  type: ClusterIP
  port: 80

log:
  jobname: carat-dash-be-prd

app:
  port: 3000  # Internal port where NestJS is running

env:
  DATABASE_HOST: "10.8.200.181"
  DATABASE_PORT: "5432"
  DATABASE_USER: "kilua"
  DATABASE_NAME: "carat-prod"

  DATABASE2_HOST: "10.8.200.181"
  DATABASE2_PORT: "5432"
  DATABASE2_USER: "kilua"
  DATABASE2_NAME: "carat-prod"

  REDIS_HOST: "10.8.200.182"
  REDIS_PORT: "6379"

  REDIS2_HOST: "10.8.200.182"
  REDIS2_PORT: "6379"

secretName: carat-prd-secrets

resources: {}