# values.yaml
namespace: carat-dev
image:
  # repository: $DOCKER_ACCOUNT/$IMAGE_NAME
  repository_ref: "altonium/carat-dash-be-dev:latest"
  pullPolicy: Always

service:
  name: carat-dash-be-dev
  type: ClusterIP
  port: 80

spec:
  replicas: 1

log:
  jobname: cdb-dev

app:
  port: 3000  # Internal port where NestJS is running

env:
  DATABASE_HOST: "10.8.200.181"
  DATABASE_PORT: "5432"
  DATABASE_USER: "kilua"
  DATABASE_NAME: "carat-dev"

  DATABASE2_HOST: "10.8.200.181"
  DATABASE2_PORT: "5432"
  DATABASE2_USER: "kilua"
  DATABASE2_NAME: "carat-dev"

  REDIS_HOST: "10.8.200.182"
  REDIS_PORT: "6379"
  REDIS_PREFIX: "cdbd"

  REDIS2_HOST: "10.8.200.182"
  REDIS2_PORT: "6379"

  CARAT_DISBURSE_HOST: "10.8.3.146"
  CARAT_DISBURSE_PORT: "3500"

  APP_ENV: "dev"


secretName: carat-dev-secrets

resources: {}