apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-promptail-config
  namespace: {{ .Values.namespace }}
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push
        tenant_id: carat

    scrape_configs:
      - job_name: {{ .Values.log.jobname }}
        static_configs:
          - targets:
              - localhost
            labels:
              job: {{ .Values.log.jobname }}
              __path__: /app/logs/*.log   # Promtail looks for logs in /app/logs

  # Add the loki-url key here
  loki-url: "http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push"