apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sleep', '36000']
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  restartPolicy: Never