name: Deploy Carat Dev/Stg to Cluster
run-name: Deploy ${{ github.event.inputs.DEPLOY_APP }} to ${{ github.event.inputs.DEPLOY_ENV }} (${{ github.event.inputs.DOCKER_IMAGE_SHA || github.event.inputs.DOCKER_IMAGE_TAG }})

on:
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        description: 'Type Deploy to confirm'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.CONFIRMATION }}" != "deploy production" ]; then
            echo "Confirmation failed. Please type 'deploy production' to confirm."
            exit 1
          fi



